// ACTIONS FOR POSTS
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const POSTS_ERROR = "POSTS_ERROR";

// ACTIONS FOR AUTHENTICATION/AUTHORIZATION
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
